### ISSUE TITLE
Could not access KVM kernel module

### ISSUE THREAD

**Issue by jonnius** [ubports/utqemu#5]
After applying #4 I hit the next issue trying to start utqemu:
```
WARNING: Image format was not specified for '/home/jonatan/snap/utqemu/common/ubuntu-touch-mainline-generic-amd64.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
Could not access KVM kernel module: Operation not permitted
qemu-system-x86_64: failed to initialize KVM: Operation not permitted
```
Adding myself to group `kvm` did not help. `sudo chmod 666 /dev/kvm` didn't solve the issue as well. No errors in `journalctl` meanwhile.

OS: Ubuntu 20.04

**Comment by mariogrip** [comment]
I assume you rebooted after adding yourself to the group? also do you have other VM running, like virtualbox or something along those lines? since you can only use 1 type at the same time.

**Comment by jonnius** [comment]
I do not have another VM running, at least not knowingly. But there seems to be something using `kvm_amd`, which uses `kvm` according to `lsmod`:
```
kvm_amd                98304  4
ccp                    86016  1 kvm_amd
kvm                   663552  1 kvm_amd
```
Any idea how to find out what that could be?

And yes, I rebooted after adding myself to the group.

**Comment by kkkmuher** [comment]
Same problem on Ubuntu 18.04. I can help developer to debug this one, just message me

**Comment by abmyii** [comment]
I think this is because `qemu-virgil` is a snap and snaps are confined, as well as from `kvm`. I found this thread (https://forum.snapcraft.io/t/nemu-kvm-permission-denied/11855) which suggested this command to fix it:
`sudo snap connect qemu-virgil:kvm`

**Comment by jonnius** [comment]
Thanks @abmyii, the command in this case is `sudo snap connect utqemu:kvm`.
